version: '3'

services:
    server:
        build: ./docker/server
        container_name: lemon-server
        volumes:
            - .:/app
            - ./.config:/root/.config
        ports:
            - 9099:80
        working_dir: /app/server
        tty: true
        shm_size: 2g
        command: bash -c "service nginx start && rm -f /tmp/.X1-lock && npm install && node index.js"